import { z } from 'zod';

export const UniversitySchema = z.object({
  name: z.string().min(2, 'University name is required'),
  shortName: z.string().min(1, 'Short name is required'),
  type: z.enum(['Public Research', 'Private Premier', 'International Branch']),
  qsRank: z.string().optional().nullable(),
  location: z.string().min(2, 'Location is required'),
  city: z.string().optional().nullable(),
  state: z.string().optional().nullable(),
  image: z.string().url().optional().or(z.literal('')),
  logo: z.string().url().optional().or(z.literal('')),
  tuitionBachelor: z.string().optional().nullable(),
  tuitionMaster: z.string().optional().nullable(),
  tuitionPhd: z.string().optional().nullable(),
  hostelMonthly: z.string().optional().nullable(),
  emgsYearly: z.string().optional().nullable(),
  avgTuition3Yr: z.number().optional().nullable(),
  registrationDeposit: z.number().optional().nullable(),
  livingCostTier: z.enum(['Low-Mod', 'Moderate', 'High']).optional().nullable(),
  livingCostMonthly: z.number().optional().nullable(),
  description: z.string().optional().nullable(),
  highlights: z.array(z.string()).optional().nullable(),
  intakeMonths: z.string().optional().nullable(),
  emgsFeeMYR: z.number().optional().nullable(),
  miscFeesMYR: z.number().optional().nullable(),
  totalInitialMYR: z.number().optional().nullable(),
  initialBreakdownNotes: z.string().optional().nullable(),
  websiteUrl: z.string().url().optional().or(z.literal('')),
});

export const ProgramSchema = z.object({
  title: z.string().min(2, 'Program title is required'),
  universityId: z.string().min(1, 'University selection is required'),
  degreeLevel: z.string().min(1, 'Degree level is required'),
  faculty: z.string().min(2, 'Faculty is required'),
  badgeType: z.enum(['verified', 'flagship', 'australian', 'qs300', 'topuk']).optional().nullable(),
  badgeText: z.string().optional().nullable(),
  duration: z.string().min(1, 'Duration is required'),
  durationYears: z.number().optional().nullable(),
  intakeMonths: z.string().min(1, 'Intake months are required'),
  scholarship: z.string().optional().nullable(),
  tuitionMYR: z.number().min(0, 'Tuition must be a positive number'),
  firstYearFeeMYR: z.number().optional().nullable(),
  secondYearFeeMYR: z.number().optional().nullable(),
  thirdYearFeeMYR: z.number().optional().nullable(),
  fourthYearFeeMYR: z.number().optional().nullable(),
  emgsFeeMYR: z.number().optional().nullable(),
  miscFeesMYR: z.number().optional().nullable(),
  totalInitialMYR: z.number().optional().nullable(),
  miscBreakdown: z.string().optional().nullable(),
  pakistanNotes: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  academicReq: z.string().optional().nullable(),
  englishReq: z.string().optional().nullable(),
  minGpa: z.string().optional().nullable(),
  documentsReq: z.array(z.string()).optional().nullable(),
});

export const InquirySchema = z.object({
  studentName: z.string().min(2, 'Full name must be at least 2 characters'),
  phone: z.string().min(3, 'WhatsApp / Phone number is required'),
  email: z.string().email().optional().or(z.literal('')),
  city: z.string().optional().nullable(),
  qualification: z.string().optional().nullable(),
  programInterest: z.string().optional().nullable(),
  programId: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
});

export const BulkProgramRowSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  universityName: z.string().min(1, 'University Name is required'),
  degreeLevel: z.string().min(1, 'Degree Level is required'),
  faculty: z.string().default('General'),
  duration: z.string().default('3 Years'),
  intakeMonths: z.string().default('January, May, September'),
  tuitionMYR: z.coerce.number().default(0),
  emgsFeeMYR: z.coerce.number().default(3500),
  miscFeesMYR: z.coerce.number().default(6000),
  totalInitialMYR: z.coerce.number().default(9500),
  scholarship: z.string().optional(),
  academicReq: z.string().optional(),
  englishReq: z.string().optional(),
});

